### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by bdpettway19** [bdpettway19/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://bdpettway19.github.io/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8/) and meets the following criteria:

- [x] Each of the following elements is used appropriately, at least once: `h1`, `h2`, `p`, `img`, `li`, `a`
- [x] At least one of the following elements is used: `ol`, `ul`
- [x] At least one external image is used and links to the page it came from

**Comment by chrisvfritz** [comment]
This looks mostly good! I just see a few issues:

### Some missing closing tags

There's an opening `<p>` tag that's missing a closing `</p>` tag, as well as a couple opening `<li>` tags where the closing tags are missing the `/`.

### Only `li` elements are allowed inside `ul` or `ol` elements

It looks like you wanted to create sublists like this:

``` html
<li>NASA Engineer</li>
  <p>Experience building spaceships</p>
  <p>Experience building spaceguns</p>
```

The way you'd actually achieve this is by putting the list items inside the `li` element, like so:

``` html
<li>
  NASA Engineer
  <ul>
    <li>Experience building spaceships</li>
    <li>Experience building spaceguns</li>
  </ul>
</li>
```

### `p` elements surrounding `ul` elements

The `p` elements around the `ul` elements are actually unnecessary and do look a little strange, since lists aren't typically thought of as paragraph content.

---

Can you update the code, then comment on this issue to let me know when it's ready for another look? If you have any questions, also please don't hesitate to ask! 😄

**Comment by bdpettway19** [comment]
I've updated my code and It's ready for you to take another look at. Thanks!

**Comment by chrisvfritz** [comment]
It's looking a little better! 🎈 I notice some `li` elements with corrected closing tags. I also see that you've updated the code inside your `ul`, although it's still not _quite_ right. Here are the remaining issues I'm still seeing:

### An opening `<p>` tag that's missing a closing `</p>` tag

Scan your code closely to see if you can find it. One trick that may make this easier is to highlight all your code in Atom, then select `Edit` -> `Lines` -> `Auto Indent` from the top menu.

### Only `li` elements are allowed _directly_ inside `ul` or `ol` elements

You'll notice a subtle difference between the example code I suggested:

``` html
<li>
  NASA Engineer
  <ul>
    <li>Experience building spaceships</li>
    <li>Experience building spaceguns</li>
  </ul>
</li>
```

and your code:

``` html
<li>NASA Engineer</li>
  <ul>
    <li>Experience building spaceships</li>
    <li>Experience building spaceguns</li>
  </ul>
```

In your code, the `ul` is still outside the `li`, so its parent element is the other `ul`, which is _not_ allowed in HTML. There's also another element directly inside a `ul` that isn't wrapped by an `li` element. 

Does that make sense or do you have questions?

### `p` elements surrounding `ul` elements

The unnecessary `p` elements around the `ul` elements are all still in the code. Let me know if you have questions I can answer about this.

**Comment by bdpettway19** [comment]
I've added the final changes Chris. I believe I have all the requirements necessary for completion.

**Comment by chrisvfritz** [comment]
This is definitely an improvement! I'm still seeing one element directly inside a `ul` element that isn't an `li`. It seems like there's still a disconnect there, so flag me down during class tomorrow and we can figure out what it is. 🙂

**Comment by bdpettway19** [comment]
I think I've figured out the problem. It was actually right in front of my face the whole time. I believe my latest upload is what you are looking for.

**Comment by chrisvfritz** [comment]
Much better! Nice work. :shipit:
